CREATE TABLE FOOD (
    ID INTEGER PRIMARY KEY ASC,
    LABEL VARCHAR(255) NOT NULL,
	CATEGORY VARCHAR(255) NOT NULL,
	PURCHASE_DATE DATE NOT NULL,
	WARNING_DATE DATE NOT NULL,
	TOSS_DATE DATE NOT NULL
);

CREATE INDEX id_index
ON FOOD (ID);







INSERT INTO FOOD (LABEL, CATEGORY, PURCHASE_DATE, WARNING_DATE, TOSS_DATE)
VALUES (
        'Apple', 
        'Fruit', 
        DATE(), 
        (select DATE(DATE(), '+'|| WARNING_INTERVAL_DAYS || ' days') from food_expiry where LABEL = 'Fruit'), 
        (select DATE(DATE(), '+'|| TOSS_INTERVAL_DAYS || ' days') from food_expiry where LABEL = 'Fruit')
);





--DOESN'T WORK


declare @TODAY as DATE = GETDATE();

declare @WARNING_DAYS as INT = SELECT @WARNING_DAYS = SELECT WARNING_INTERVAL_DAYS FROM INVENTORY.EXPIRY WHERE LABEL = 'Fruit';

declare @TOSS_DAYS INT = SELECT @TOSS_DAYS = SELECT TOSS_INTERVAL_DAYS FROM INVENTORY.EXPIRY WHERE LABEL = 'Fruit';

INSERT INTO FOOD (LABEL, CATEGORY, PURCHASE_DATE, WARNING_DATE, TOSS_DATE)
VALUES ('Apple', 'Fruit', @TODAY, select DATEADD(day, @WARNING_DAYS, @TODAY), select DATEADD(day, @TOSS_DAYS, @TODAY);




INSERT INTO FOOD (LABEL, CATEGORY, PURCHASE_DATE, WARNING_DATE, TOSS_DATE)
VALUES ('Apple', 'Fruit', DATE(), DATE(DATE(), '+'|| select FOOD_EXPIRY_WARNING_INTERVAL_DAYS from food_expiry|| ' days'), DATE(DATE(), '+'|| select FOOD_EXPIRY_TOSS_INTERVAL_DAYS from food_expiry|| ' days');