CREATE TABLE FOOD_STORAGE_TYPE (
    INDX int,
    LABEL varchar(255)
);

INSERT INTO FOOD_STORAGE_TYPE (INDX, LABEL)
VALUES (0,'Shelf');

INSERT INTO FOOD_STORAGE_TYPE (INDX, LABEL)
VALUES (1,'Refrigerate');

INSERT INTO FOOD_STORAGE_TYPE (INDX, LABEL)
VALUES (2,'Freeze');