CREATE TABLE ITEM_TYPE (
    INDX int,
    LABEL varchar(255)
);

INSERT INTO ITEM_TYPE (INDX, LABEL)
VALUES (0,'System');

INSERT INTO ITEM_TYPE (INDX, LABEL)
VALUES (1,'Food');

INSERT INTO ITEM_TYPE (INDX, LABEL)
VALUES (2,'Vehicles');