CREATE TABLE ITEM_TYPE (
    ID INTEGER PRIMARY KEY ASC,
    LABEL VARCHAR(255)
);

INSERT INTO ITEM_TYPE (LABEL)
VALUES ('System');

INSERT INTO ITEM_TYPE (LABEL)
VALUES ('Food');

INSERT INTO ITEM_TYPE (LABEL)
VALUES ('Vehicles');