CREATE TABLE VEHICLES (
    INDX int,
    YR varchar(4),
    MAKE varchar(255),
    MODEL varchar(255),
	SUB_MODEL varchar(255),
    COLOR varchar(255),
	DRIVE varchar(3),
	FUEL varchar(255)
);

INSERT INTO VEHICLES (INDX, YR, MAKE, MODEL, SUB_MODEL, COLOR, DRIVE, FUEL)
VALUES (0,'2012', 'LEXUS', 'IS250', 'Base', 'RED', 'AWD', 'PREMIUM GAS');

INSERT INTO VEHICLES (INDX, YR, MAKE, MODEL, SUB_MODEL, COLOR, DRIVE, FUEL)
VALUES (1,'2011', 'FORD', 'F-250', 'LT', 'WHITE', '4WD', 'DIESEL');

INSERT INTO VEHICLES (INDX, YR, MAKE, MODEL, SUB_MODEL, COLOR, DRIVE, FUEL)
VALUES (2,'1991', 'FORD', 'F-250', 'XLT Lariat', 'RED', 'RWD', 'DIESEL');

INSERT INTO VEHICLES (INDX, YR, MAKE, MODEL, SUB_MODEL, COLOR, DRIVE, FUEL)
VALUES (3,'1992', 'NISSAN', '240SX', 'Base', 'GREEN', 'RWD', 'GAS');

INSERT INTO VEHICLES (INDX, YR, MAKE, MODEL, SUB_MODEL, COLOR, DRIVE, FUEL)
VALUES (4,'2007', 'SUBARU', 'IMPREZA WRX', 'STi Limited', 'SILVER', '4WD', 'PREMIUM GAS');

INSERT INTO VEHICLES (INDX, YR, MAKE, MODEL, SUB_MODEL, COLOR, DRIVE, FUEL)
VALUES (5,'2002', 'SUZUKI', 'SV650', '', 'BLACK', 'RWD', 'GAS');

INSERT INTO VEHICLES (INDX, YR, MAKE, MODEL, SUB_MODEL, COLOR, DRIVE, FUEL)
VALUES (6,'2007', 'SUZUKI', 'GSX1300R HAYABUSA', '', 'BLUE', 'RWD', 'GAS');

INSERT INTO VEHICLES (INDX, YR, MAKE, MODEL, SUB_MODEL, COLOR, DRIVE, FUEL)
VALUES (7,'1977', 'KUBOTA', 'L185DT', '', 'ORANGE', '4WD', 'DIESEL');