CREATE TABLE VEHICLES (
    ID INTEGER PRIMARY KEY ASC,
    YR VARCHAR(4) NOT NULL,
    MAKE VARCHAR(255) NOT NULL,
    MODEL VARCHAR(255) NOT NULL,
	SUB_MODEL VARCHAR(255),
    COLOR VARCHAR(255),
	DRIVE VARCHAR(3),
	FUEL VARCHAR(255) NOT NULL
);

INSERT INTO VEHICLES (YR, MAKE, MODEL, SUB_MODEL, COLOR, DRIVE, FUEL)
VALUES ('2012', 'LEXUS', 'IS250', 'Base', 'RED', 'AWD', 'PREMIUM GAS');

INSERT INTO VEHICLES (YR, MAKE, MODEL, SUB_MODEL, COLOR, DRIVE, FUEL)
VALUES ('2011', 'FORD', 'F-250', 'LT', 'WHITE', '4WD', 'DIESEL');

INSERT INTO VEHICLES (YR, MAKE, MODEL, SUB_MODEL, COLOR, DRIVE, FUEL)
VALUES ('1991', 'FORD', 'F-250', 'XLT Lariat', 'RED', 'RWD', 'DIESEL');

INSERT INTO VEHICLES (YR, MAKE, MODEL, SUB_MODEL, COLOR, DRIVE, FUEL)
VALUES ('1992', 'NISSAN', '240SX', 'Base', 'GREEN', 'RWD', 'GAS');

INSERT INTO VEHICLES (YR, MAKE, MODEL, SUB_MODEL, COLOR, DRIVE, FUEL)
VALUES ('2007', 'SUBARU', 'IMPREZA WRX', 'STi Limited', 'SILVER', '4WD', 'PREMIUM GAS');

INSERT INTO VEHICLES (YR, MAKE, MODEL, SUB_MODEL, COLOR, DRIVE, FUEL)
VALUES ('2002', 'SUZUKI', 'SV650', '', 'BLACK', 'RWD', 'GAS');

INSERT INTO VEHICLES (YR, MAKE, MODEL, SUB_MODEL, COLOR, DRIVE, FUEL)
VALUES ('2007', 'SUZUKI', 'GSX1300R HAYABUSA', '', 'BLUE', 'RWD', 'GAS');

INSERT INTO VEHICLES (YR, MAKE, MODEL, SUB_MODEL, COLOR, DRIVE, FUEL)
VALUES ('1977', 'KUBOTA', 'L185DT', '', 'ORANGE', '4WD', 'DIESEL');